import React from "react";
// import HeroSection from "./components/HeroSection";
import AboutSection from "./components/AboutSection";
import AnimatedArrow from "./components/AnimatedArrow";
import PlacementSection from "./components/PlacementSection";
import CoursesOffered from "./components/CoursesOffered";
import LatestNews from "./components/LatestNews";
import NewsAndEvents from "./components/NewsAndEvents";
import Happenings from "./components/Happenings";
import OurInstitutions from "./components/OurInstitutions";
import LifeSeg from "./components/LifeSeg";
import WantMoreDetails from "./components/WantMoreDetails";
import ChatBot from "./components/Chatbot";
import CompaniesTieUps from "./components/CompanyTieUps";
import GoogleAdsScript from "./components/GoogleAdsScript";
export const metadata = {
  title: "Saroj College of Group | Saroj Educational Group (SEG)",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <>
      {/* <ChatBot/> */}
      <GoogleAdsScript/>
      <AboutSection />
      <LatestNews />
      <CompaniesTieUps/>
      <WantMoreDetails/>
      <PlacementSection />
      <CoursesOffered />
      <NewsAndEvents />
      <Happenings />
      <OurInstitutions />
      <LifeSeg />
    </>
  );
};
export default Home;
