import React from "react";
import HeroSection from "./components/HeroSection";
export const metadata = {
  title: "Saroj College of Group | Saroj Educational Group (SEG)",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <div className="">
      <HeroSection/>
      
    </div>
  );
};
export default Home;
